[package]
name = "aoc"
version = "0.1.0"
edition = "2021"

[dev-dependencies]
criterion = "0.8"


[[bench]]
name = "day01_secret_entrance"
path = "src/01_secret_entrance/bench.rs"
harness = false

[[bin]]
name = "01_secret_entrance"
path = "src/bin/01_secret_entrance.rs"

[[bin]]
name = "02_gift_shop"
path = "src/bin/02_gift_shop.rs"